### ISSUE TITLE
install page

### ISSUE THREAD

**Issue by liuj-42** [crypto-arbitrage-bot/CAB-site#1]
## tasks:
- [x] create content for the install page
- [ ] find a library to hold a video for the install video
- [x] style the install page
