### ISSUE TITLE
navbar complete

### ISSUE THREAD

**Issue by liuj-42** [crypto-arbitrage-bot/CAB-site#2]
## tasks:
- [x] link to about page
- [x] link to install page
- [x] link to contact page
- [x] link to github page
    - [ ] make github link look pretty
 - [x] style the navbar
     - [x] 25% complete
     - [x] 50% complete
     - [ ] 75% compete
     - [x] 100% complete  

- [x] have the accent color of text on the active page be different
