### ISSUE TITLE
contact page

### ISSUE THREAD

**Issue by liuj-42** [crypto-arbitrage-bot/CAB-site#3]
## tasks:
- [x] create a form to send email
    - [x] style the form
- [ ] create an emailjs account to do stuff with  
    - https://www.emailjs.com/docs/examples/vuejs/
    - https://www.freecodecamp.org/news/send-emails-from-your-vue-application/
- [ ] connect emailljs with the actual contact page
